
---

loopback: 172.16.0.12

spine01_interfaces:
  - name: xe-0/0/0
    unit: 11
    addr: 192.168.11.6

spine02_interfaces:
  - name: xe-0/0/1
    unit: 21
    addr: 192.168.21.6

server_interfaces:
  - name: xe-0/0/2
    unit: 31
    addr: 192.168.31.6
  - name: xe-0/0/3
    unit: 41
    addr: 192.168.41.6
